### PR TITLE
Added UUID to the cloudformation template as a parameter

### PR DESCRIPTION
**Pull request by SonalOjha**

### CODE REVIEW

**Comment by AlexOugh** [comment]
Now sure what the purpose of this module is. Is a stack creating by this module instead of condensation?

**Comment by SonalOjha** [comment]
Yes, these changes are to run the cftemplate through API rather than condensation.

**Comment by sauravlahiri** [comment]
Looks good.

**Comment by AlexOugh** [comment]
Can you tell me when to run the cftemplate using this API instead of condensation?

**Comment by SonalOjha** [comment]
So when we create ess appliance through portal a lambda function is triggered which would trigger a cftemplate providing it all the required parameters

**Pull request merged**
