### PR TITLE
Removed enhancesnapshot code from aws-services

### PR DESCRIPTION
**Pull request by bhargavapratik**
Removed enhancesnapshot code from aws-services

### CODE REVIEW

**Review by RajkumarShivage — COMMENTED** [review]
Will this remove the commit history too?

**Comment by bhargavapratik** [comment]
No, only from develop branch.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by RajkumarShivage** [comment]
I had shared one github link on how to remove entire history from GitHub. Have you had looked into it?

**Review by RajkumarShivage — APPROVED** [review]

**Review by kameshsg — APPROVED** [review]
LGTM

**Pull request merged**
